[theme]
base = "dark"
primaryColor = "#FF7A50"
backgroundColor = "#161210"
secondaryBackgroundColor = "#211A15"
textColor = "#F3E9DA"
font = "sans serif"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
